name: Groups MS CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

permissions:
  contents: read

jobs:
  ci:
    uses: Projet-technique-Altair/altair-ci/.github/workflows/groups-ci.yml@main
    with:
      rust_toolchain: stable
